### PR TITLE
feat: Added a dynamic form field system from manifest data

### PR DESCRIPTION
**Pull request by Vafilor**
closes onepanelio/core#110

### CODE REVIEW

**Comment by rushtehrani** [comment]
1. Is this Argo's validation? 
2. Possible to make `value` not required in YAML?
3. Also if we can implement 2, would need to figure out how to add a `required: true` field which will require the user filling in the form or passing this via API/CLI to enter it.
image

**Comment by rushtehrani** [comment]
Minor spacing issue between form title and the first input element.
image

**Comment by Vafilor** [comment]
@rushtehrani

1. That is the default validation yes, I did not add that part.
2/3. Yes, we can do that. A simple approach might be to have Argo ignore the field if there is no value, like we do with the type/options. Then, the web client can decide if it is required or not (API can also) and it'll inject it if it is.

**Comment by Vafilor** [comment]
@rushtehrani Alrighty, the develop branch (and docker image tag) has these changes.

It required both UI and API.

Change log
* value is no longer required in the fields
* addition of required field (does not apply to radio)
* addition of inputType field - only applicable to `input.text` supports HTML types including 
  * text
  * password
  * number

**Comment by rushtehrani** [comment]
> * addition of required field (does not apply to radio)

Is this not possible?

## UI issues
1. Distance between form title and first input is still off.
2. Modal bottom padding is really large, should be the same top padding.
3. No need for the snackbar here since we hav inline errors.
image

**Comment by rushtehrani** [comment]
Also, instead of requiring `inputType`, wouldn't it make sense to use:
- `input.number` 
- `input.password`

Since in `input.text`, `text` is the `type` of `input` in `<input type="text" />`?

**Comment by Vafilor** [comment]
> Also, instead of requiring `inputType`, wouldn't it make sense to use:
> 
> * `input.number`
> * `input.password`

> Since in `input.text`, `text` is the `type` of `input` in `<input type="text" />`?

We can do that, I don't think there will be any conflict with the types.

Regarding other UI issues, will fix.

Regarding Radio, will take a look at. I figured radio would be always required, but I suppose there are cases where it might be optional.

**Comment by Vafilor** [comment]
@rushtehrani When you get a chance, please check out the updated branch.

One key difference is the bottom actions now don't scroll with the content  - this is most visible on smaller screens. Let me know what you think of the title/footer now.

Also, regarding the vertical alignment of the inputs - can you check out https://material.angular.io/components/form-field/overview#form-field-appearance-variants the outline form field there and see if you see the same issue? It looks like thats how it is with Angular Material, but I might be missing something visually.

**Comment by rushtehrani** [comment]
> When you get a chance, please check out the updated branch.

Will do, so 1-4 (minus the points you mentioned) and the input changes are addressed now?

> Also, regarding the vertical alignment of the inputs - can you check out

Seems to be better aligned than ours:
ours:
image
theirs:
image

**Comment by Vafilor** [comment]
@rushtehrani Okay, adjustment has been pushed up.

**Comment by rushtehrani** [comment]
@Vafilor was using the `develop` tag and that's 3 days old. No tag for these yet?

**Comment by Vafilor** [comment]
@rushtehrani Just a few - going to merge it into develop to trigger it.

**Comment by rushtehrani** [comment]
> One key difference is the bottom actions now don't scroll with the content - this is most visible on smaller screens. Let me know what you think of the title/footer now.
Possible to just have the content are expand instead of scroll as more fields are added?
image

**Comment by Vafilor** [comment]
@rushtehrani Not sure I follow - do you think the window is too small? We can change the window height.

**Comment by rushtehrani** [comment]
> @rushtehrani Not sure I follow - do you think the window is too small? We can change the window height.

Instead of having the form content area scroll, can we just have the modal expand and then the whole page would scroll instead?

**Pull request merged**
